# Do not commit the credentials
username=root
password=password
dbhostname=localhost
dbport=5432
dbname=scb
db=postgresql
url=jdbc:postgres//localhost:5432//scbdb
#username=<username>
#password=<password>
#dbhostname=<hostname>
#dbport=<port>
#dbname=<dbname>
#db=<db>